### ISSUE TITLE
https://www.onyxia.sh: why the "Pricing" link?

### ISSUE THREAD

**Issue by bzg** [InseeFrLab/onyxia#402]
Clicking on the link opens a modal window explaining that "It's libre software" but does not answer what people may ask themselves about the "Pricing": so I read it as "There is no pricing because it's libre software", which is a wrong inference.

I suggest renaming this link to "FLOSS" as in "Free Libre Open Source Software".

**Comment by garronej** [comment]
I used to explicitly state why it's free for the end user:  
"It's paid for by the France's taxpayers’ money."  
 But I was kindly ask to remove this. 😄  

The reasoning behind this link is that, we are afraid to be perceived as a startup because of how much production value and emphasis on marketing we put in the landing page.  
We don’t want people wondering, "what are they trying to sell me...? 🧐"  

At least I know that, before doing some research on a tool I want to know what I'm getting myself into so the `pricing` or `plan` is always one of the first section I'm looking for.  

Anyway, I see the problem, we shouldn't implicitly convey the idea that open source software is monetarily free.  
I'll rename the link.

**Comment by garronej** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6702424/199473567-91c406e9-5f0c-4b0f-8292-aac422261db1.png">

**Comment by bzg** [comment]
> We don’t want people wondering, "what are they trying to sell me...?

I understand this concern but people are usually fine wondering about this while still using the "free" stuff :)

> I'll rename the link.

Thanks a lot!
