### ISSUE TITLE
Deploy Onyxia on OpenShift using Routes

### ISSUE THREAD

**Issue by sergkoudi** [InseeFrLab/onyxia#413]
Hi,
We are trying to deploy Onyxia on OpenShift cluster.
OpenShift recommends using [Routes](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html) instead of Ingress. 
Is it possible to deploy Onyxia using Routes, how? Are you planning to support it?

**Comment by fcomte** [comment]
Hello

I think you are using this chart : 
https://github.com/InseeFrLab/helm-charts/tree/master/charts/onyxia

And you want to add an option to use route in stead of ingress? 

We don't have any openshift cluster , so it's quite hard for us to test that.
Moreover if we want to support it, we will need to support it for all charts deployed by Onyxia.

As a first try to deploy Onyxia you can disable ingress and create route yourself. You need to create openshift routes so that the UI request the api with the same host and /api  context path. 

@olevitt maybe you have other ideas?

**Comment by sergkoudi** [comment]
Hello,

I tryed to disable ingress and create an OpenShift route manualy.
It seams it worked, but there is an issue with onyxia-web (Nginx) container that doesn't start. This is because OpenShift is [assining user ID arbitrarily](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#use-uid).

The issue with UID can be solved only by modifying Dockerfile of onyxia-web ([bitnami/nginx](https://hub.docker.com/r/bitnami/nginx) image is a candidate for a base Nginx image). But I assume that services deployed by Onyxia will potentially have the same issue.
