### ISSUE TITLE
Call onboarding when switching project 

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#545]
As an onyxia administrator i want that the namespace creation is handle at login of user and not a first service launched.

Indeed, i could have implemented some kind of namespace onboarding that deploy some resource in the namespace at creation and needed before service is launched.

The first step for that is:
- [ ] call /onboarding endpoint already existing at conection for the projet that is selected. When i switch project the ui could recould onboarding that does nothing if the namespace exist.

It could have next step like :
- [ ] showing the process of onboarding at user the first time if namespace and bucket do not exists then call onboarding and wait for them with a user experience mapped on it.

**Comment by fcomte** [comment]
Onboarding API has a group parameter : this group is the owner of the project ( which is the name of the oidc group )

You should get it from the api because it's included in the model as shown below : 
https://github.com/InseeFrLab/onyxia-api/blob/ed09d5660ec582f3e14ed79ea1160cf15bce0eb2/onyxia-model/src/main/java/fr/insee/onyxia/model/project/Project.java#L10C1-L11C26

I think you don't get it from the API because I don't see it in the web model : 
https://github.com/InseeFrLab/onyxia-web/blob/15ef50db369d02d80784b2ad15598a124728865a/src/core/ports/OnyxiaApi.ts#L186

This is what you should send to the onboarding call.

**Comment by garronej** [comment]
It's done in 2.21.0.  
Note to prevent any missunderstanding that if Bob and Alice both belong to `project-foo`, when Alice select `project-foo` the `POST /api/onboarding` is called but when Bob do the same it won't be because the goup has already been onboarded by Alice.  

Also the transparent splashcreen gets displayed, preventing any user interaction while the onboarding process is ongoing.

**Comment by johnksv** [comment]
Great improvement! However this feature created some issues if onyxia is run as single namespace. I think the fix should be done in the backend and has thus created this PR: https://github.com/InseeFrLab/onyxia-api/pull/245
