### ISSUE TITLE
generate a user password random for each service

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia#589]
From the user experience in onyxia we:
- copy paste pasword from the shortcut
- check the password in readme/notes.txt 

It seems to me that it could be a security improvement without reducing user experience if onyxia ui can generate a random password for each service.

It's useful too for card that allow sharing servces like postgres.
 The actual experience let the user easily communicate his password,  if he is not advertise. Doing this, he opens the gate to all of his interactive services (really easy to find url through grafana for exemple for another user).

**Comment by alexisdondon** [comment]
Maybe to discuss with @fcomte for interactive services i see no problem. For card like mlflow it could be trick like today if the user change its onyxia password it can have trouble when restarting its service based on a pvc postgres already launch with a previous password.

**Comment by fcomte** [comment]
We can create a new x-onyxia syntax to generate random string for any value.
But you can also generate this random string yourself in helm.
 
To make the automatic copy of this password I think we can look for a regexp inside Notes.txt for "password: "

**Comment by fcomte** [comment]
- [ ] generate une new section : service.randomPassword https://github.com/InseeFrLab/onyxia/blob/b5593567904f8a8c7bc31e6852e88a6e12cb30b4/web/src/core/ports/OnyxiaApi/XOnyxia.ts#L20
- [ ] modify rule for copy paste at lauch time with a regexp "password: a-zA-Z0-9*"
- [ ] modify UX for the password by generating a new button on each services with a key allowing to copy the password.

We will implement this random on our main opensource catalog for IDE

**Comment by garronej** [comment]
Done.  
- A new key is now available in the `x-onyxia` context: [`service -> oneTimePassword`](https://github.com/InseeFrLab/onyxia/blob/3055c94161796367bf21b888017c18ae33be0627/web/src/core/ports/OnyxiaApi/XOnyxia.ts#L30). This is dynamically generated and can be used by chart authors as a service password, substituting for `project -> password` (or \`user -> password\`, which is simply an alias for the former).   
- Chart authors using the one-time password must ensure it appears in the package notes, prefixed by \`password: \`. Otherwise, the Onyxia GUI won't automatically copy it to the clipboard.  

As a positive side effect of this update, the "Password" button has been removed from the `MyServices` button bar. The `README` button on the service card has also been removed. The `Open` button now performs the function that the `README` button used to serve.  
For services without an associated HTTP URL, the button is labeled "README".
