### ISSUE TITLE
Services and kube command prompt overlap when navigator zoom is too high

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/onyxia#633]
Hi,
I have some overlapping in the UI of onyxia under some specific zoom levels at least in the _"my services"_ page.

Under
- firefox 115.3.1esr (64 bits) and edge 118.0.2088.46 (64 bits)
- screen size 1920 x 1080
- different levels of zoom

I have : 

| screen shot | is the render ok ? |
| --- | --- |
| ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/5bf59a1f-5c28-4a11-b269-f925d485a179) | yes 😄  |
| ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/15bf9b94-2155-4f0c-851a-9bf5ff91828d) | no 😭 |
| ![image](https://github.com/InseeFrLab/onyxia/assets/55583423/ddd8f8a8-52c6-40f5-bc13-7a60dbc89b7b) | no 😭 |

Thanks in advance.
I know this might not be a priority.

**Comment by garronej** [comment]
Hello @odysseu,  

Thanks for reporting
Did you had complains about this?  

If we introduced https://github.com/garronej/screen-scaler it was precisely to avoid wasting too much time buiding a responsive design.  

It was a problem, accessibility wise to prevent the zoom so we enabled it but as a result thinking "ok well it will break when the users zoom but at least they will be able to read".  

That beeing said, if it turns out the app is completely unusable at some level of zoom there might be some quick win we can implement.

**Comment by odysseu** [comment]
No complains so far, personally I don't have issues at classic zoom levels and this is probably the case of 99% of users.

- maybe the vertical and horizontal margins don't need to get so big (this reminds me of your https://github.com/InseeFrLab/onyxia/issues/603#issuecomment-1739249732 a few weeks back).
- maybe the prompt could be the length of `min(length of the command; the rest of the space left between "my services" and the right side of the UI)`.

**Comment by garronej** [comment]
Thanks a lot for the advises!

**Comment by fcomte** [comment]
can we close this ? @garronej

**Comment by garronej** [comment]
I think it's a won't fix.  
Onyxia is just not responsive at the moment, we have to make peace with that until we commit to implementing proper responsive design.  

Thanks for reporting @odysseu though
