### ISSUE TITLE
Documentation links from services are invisible, unless you mouse over

### ISSUE THREAD

**Issue by trygu** [InseeFrLab/onyxia#706]
When on the service section of Onyxia. The **"Learn more"** button is invisible, unless you mouse over. The links are important for us, since we point the users to relevant part of our internal documentation for the use of the different services that we provide. 

![image_240](https://github.com/InseeFrLab/onyxia/assets/3669823/1278c062-58cd-4c8d-911f-3dbd5abadc85)

![image_240](https://github.com/InseeFrLab/onyxia/assets/3669823/264dae03-3512-4453-8ad7-2a9d5491d784)

**Comment by garronej** [comment]
Hello @trygu what's up?  

This behaviour is by design, I think we intend to keep it that way, the goal is to have a UI that is not too loaded as displaying to much information tend to be intimidating.   

This is however a behaviour that you can easyly customize in your instance:  

```values.yaml
onyxia:
  web:
    env:
      CUSTOM_RESOURCES: "https://example.com/onyxia-resources.zip"
      CUSTOM_HTML_HEAD: |
        <link rel="stylesheet" href="%PUBLIC_URL%/custom-resources/main.css" />
```

onyxia-resources/main.css
```css
[class*="CatalogChartCard-learnMoreButton"] {
    visibility: visible !important;
}
```  

<img width="1726" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/27de0468-9559-462f-840a-a792044629ab">

**Comment by trygu** [comment]
Hi @garronej! Thank you for the response. I was guessing it was intentional. Great to know where we can fix it (if we decide to show them).
