### ISSUE TITLE
Hide/filter unstable chart versions for non-developers

### ISSUE THREAD

**Issue by Andilun** [InseeFrLab/onyxia#709]
**Issue description**:
Currently, in the Onyxia web version dropdown menu, all versions of charts are displayed, including unstable ones (like rc or beta versions).

Our issue stems from not wanting to expose potentially unstable rc or beta versions to our users, while using the same chart repo across multiple environments.

**Example**:
<img width="483" alt="Dropdown menu issue" src="https://github.com/InseeFrLab/onyxia/assets/8294494/5e0a26c0-9a0b-4910-951e-9e9ba9cb08f8">

**Possible solution**:
A solution could be a filter that would exclude chart versions containing a hyphen '-' while not in developer mode. This solution would eliminate the need for duplicating or forking chart repositories for different environments and remove the risk of exposing users to unstable versions unless they specifically opt-in.

**Comment by garronej** [comment]
Thanks for reporting @Andilun,  

This is a bug. I'll fix it now.

**Comment by Andilun** [comment]
Thanks @garronej 🥇
 
Could a condition to allow developers to view all versions be added? Something like ```.filter(({ version }) => isDevModeEnabled ? true : !version.includes("-"))```.

**Comment by garronej** [comment]
@Andilun, sure that can be done

**Comment by fcomte** [comment]
what is the status of this issue @garronej ?

**Comment by garronej** [comment]
@fcomte @Andilun Sorry for not following up on this. The behavior was changed since it was last discuted.  
Currently the beta, alpha release candidates ect. are never selected by default but are always sown in the dropdown for selecting version in the launcher page.  
According to me, this allright, it's a bit like NPM does it. You'll never mistakingly pull an alpha but you can spin it up if you want to.  
I can still hide thoses versions in non dev mode if you're not happy with the curent state of things.  

I'll close this issue but do not hesitate to reopen.
