### ISSUE TITLE
Upgrade DuckDb within Jupyter

### ISSUE THREAD

**Issue by ericemc3** [InseeFrLab/onyxia#722]
Hi, not sure if it is the right place to ask,
but i am stuck with an old DuckDB version in my Jupyter notebook:

![image](https://github.com/InseeFrLab/onyxia/assets/17407796/b2f8ed4f-7b13-4348-aa8a-9d9f11025d7e)

I'd like to install the last one (0.9.2). How is it possible please?

**Comment by fcomte** [comment]
Hello,

here is the project for IDE stacks : https://github.com/InseeFrLab/images-datascience/

I think we identify and fix it for the next build of docker images ( available monday morning ) : https://github.com/InseeFrLab/images-datascience/pull/169 

@avouacr do you confirm ?

**Comment by ihiverlet** [comment]
Hi, 
I think the fix on duckdb version is available since monday 8. (At least, I was not able to reproduce this behavior.) 

If your service was launched before monday, I guess you can still enforce any duckdb version you want using  (for version 0.9.2)  `pip install duckdb==v0.9.2`.
However,  please bear in mind that if your service is older than 7 days it might be deleted soon due to our resources regulation policy.

If your service is newer, can you please run the following command in a terminal and give us the node name corresponding to your service so we can carry out a more in-depth investigation ? `kubectl get pods -o wide`

**Comment by ericemc3** [comment]
Hi, and thank you for the tip `pip install duckdb==v0.9.2`, after a kernel restart, i got it right! My service is indeed 2 weeks old.
