### ISSUE TITLE
Button to refresh S3 tokens is not working

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia#734]
![image](https://github.com/InseeFrLab/onyxia/assets/48868412/3cb674e8-1dc2-4849-9278-b5d32f889f57)

This button is not working anymore. I think Onyxia does not refresh because it calculated if he need to be refreshed.
This button should enforce refresh.

**Comment by alexisdondon** [comment]
@garronej @fcomte not just refresh but also refresh the jwt token as from new mechanism the problem is that when user credentials change on s3 the sts token need to be refresh.

From my understanding it could be very useful to generate sts from logout/login that's the natural way to ahve a new jwt keycloak token and ask.

a more advanced way but with a lot effort could be to ask new sts s3 token if groups and policies claims of sts token is différent from keycloak token probably the cleanest way today with more effort to add to the rule of 90% renew sts token if 90% and claims groups, policies different between oidc token and sessionToken.

**Comment by alexisdondon** [comment]
this feature could work with the next design:
- given a user that have groups or policies that is modified (two claims) 
- the user need to  deco/reco then the ui should generate a new onyxia minio oidc token with policy and groups updated.
- at least the user needs to toggle the button to renew sts.

**Comment by garronej** [comment]
@alexisdondon you're right but we arbitrated that it's not worth the effort. We implemented a session storage cache mechanism instead.
