### ISSUE TITLE
Missing policy documentation onyxia minio

### ISSUE THREAD

**Issue by 2FromField** [InseeFrLab/onyxia#808]
Follow the the Onyxia's v8 documentation on: https://docs.onyxia.sh/admin-doc/readme/data-s3. 
My “My Files” tab was not working due to a jwt token not containing the policy. 

After following the Onyxia v8 documentation: https://docs.onyxia.sh/admin-doc/readme/data-s3. My “My Files” tab was not working due to a jwt token not containing the policy. 
To solve this problem, all I had to do was fill in the “Token Claim Name” field : “policy” on Keycloack, in the client tab : “onyxia-minio/onyxia-minio-dedicated/policy”.

This step is not mentioned in the documentation:
<img width="764" alt="Capture d'écran 2024-05-16 110539" src="https://github.com/InseeFrLab/onyxia/assets/115177083/5d0bab74-20fe-4275-9215-de6b3a99d1c5">

Joey BRUNO.

**Comment by garronej** [comment]
Hello @2FromField,  

Thank you for taking the time to report.  

So you're saying we must enter `name: policy` and `token claim name: policy`?  
I though it would fallback to the the name if not provided...

**Comment by 2FromField** [comment]
Absolutely, in my case it was necessary for the whole thing to work properly. Without this information properly indicated in this field, it didn't work. The policy didn't appear in the JWT token and therefore didn't allow the link between onyxia and minIO to work.

**Comment by garronej** [comment]
Thank you again for reporting, sory about the time it must have take you to find the issue.  

I've added the missing step:  

<img width="684" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/802ab55e-d177-4977-a811-cfd4aab4db95">

**Comment by 2FromField** [comment]
Perfect !

**Comment by garronej** [comment]
By the way I saw that you've created a nice theme!  

<img width="918" alt="image" src="https://github.com/InseeFrLab/onyxia/assets/6702424/97fa0a91-d7d6-403d-84a9-bc8938d63e6a">

How did you manage to develop it? Because as far as I know it was broken until yesterday. At least the `.env.local.yaml` didn't work when using any `#` character...

**Comment by 2FromField** [comment]
Ahah thank you very much!
I was inspired by your video tutorial: https://www.youtube.com/watch?v=NrVuVXsbloA
I simply implemented my `onyxia-values.yaml` file in the `web/env` section with the elements that can be modified. That's all there is to it.

**Comment by garronej** [comment]
You mean the .env.local.yaml?  This confuse me because I tried to create a theme yesterday and I realized that it was broken since the Vite migration. 🤔   
I'm happy that it worked for you, I just can't figure out how...  

Anyway, have a nice day.

**Comment by 2FromField** [comment]
Hello Joseph,
I’m currently setting up an onyxia instance in my IS. I would like to set up the « projects » as detailed in your documentation : https://docs.onyxia.sh/admin-doc/setting-up-group-projects

I’ve tried to create a « Groups » on Keycloak and assign a « Users » to it but it doesn’t show me the dropdown on the main page to change project.

Do you have a guide or something about it ? 
Sincerely. 

BRUNO Joey
Apprenti Data/Sport-Scientist chez SEENOVATE
	📩 ***@***.***
	📞 06.80.95.89.22
	📍 Rennes
	🖥 github.com/2FromField

**Comment by olevitt** [comment]
Hi @2FromField !

Onyxia populates the list of projects based on the content of `groups` (configurable via env if you want to use another claim) claim in the JWT token.  
If your list is empty then it either means that the claim is empty or that it contains only invalid (not RFC 1123 compliant https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) values.  
Here is a few things to check : 
- Make sure you logout / relogin after any change to group membership so that keycloak re-issue a new token with the new groups
- Make sure the `groups` are included in the token (use jwt.io or other tools to inspect the token)
- Make sure the `groups` conform to RFC 1123. Notably, they can't include upercase characters and should not start with `/` (Keycloak has an option `include full path` or something like that prefix the group with a `/`. Uncheck this option)  
- Check the JSON body of the response to the API `/user/info` call, it should list the groups that have been resolved

If none of those checks help you, please create a new issue with some more context (notably the content of the `groups` claim)

**Comment by 2FromField** [comment]
Thank you Olivier for your prompt reply.
Indeed, it was just a parameter to be unchecked... The famous “Full group path” in the mapper of my “groups” role. 
It now works and I can access my project dropdown. 
Thanks a lot.

BRUNO Joey
Apprenti Data/Sport-Scientist chez SEENOVATE
	📩 ***@***.***
	📞 06.80.95.89.22
	📍 Rennes
	🖥 github.com/2FromField
