### ISSUE TITLE
Add in XOnyxiaContext Access token of user

### ISSUE THREAD

**Issue by titigmr** [InseeFrLab/onyxia#861]
We are developing an API that can manage external resources, but resources creations are managed by an Onyxia service. 

For authentication at this external resources, it could be great to inject the access token on the service launch. Then, the API verify the access token by calling the IDP and create requested resources (resources are VM).

If it not possible, do you have another solution to secure authentication for this api?

Thanks!

**Comment by garronej** [comment]
Sure! I can easily add the `accessToken` to the Onyxia context. However, I'm not sure this is necessarily the best approach since the access token is, by default, valid for less than 5 minutes—and in the Keycloak configuration, you can set this value as low as 5 seconds.

This means that by the time the service is launched, the token could already be expired.

Additionally, the token provided would be the one for the Onyxia-web OIDC client.

If you're aware of these two points and still want me to proceed with adding the `accessToken`, I can move forward with the implementation.

@fcomte, any thoughts?

**Comment by titigmr** [comment]
1. There are no mecanism to refresh token automatically? 
2. This API is implemented for Onyxia service, the OIDC client can be the same.
But in any case, it's okay for us.

**Comment by fcomte** [comment]
we can provide this overwriteDefaultWith

**Comment by garronej** [comment]
> Can we provide this as `overwriteDefaultWith`?

@fcomte Yes, that's the idea—making it accessible within the `XOnyxiaContext`, so it can be referenced as a target for `overwriteDefaultWith`.

> Is there no mechanism to refresh the token automatically?

I can refresh the token manually. However, whether it happens "automatically" depends on your context. 

- If you're a user of [oidc-spa](https://oidc-spa.dev), the token is refreshed automatically. When you call `getToken().accessToken`, you're guaranteed to receive a token with at least 90% of its TTL remaining.
  
- From your side, though, I can only provide you with both the access token and the refresh token. You'll need to make periodic POST requests to `<oidc-server-url>/protocol/openid-connect/token` with the refresh token as a parameter to obtain a new access token each time.

Would you like to explore this option? Alternatively, you could configure Keycloak to extend the lifespan of the access token, for example, to 15 minutes. This approach is quick and easy, but the trade-off is that if an access token gets compromised, it remains valid for those 15 minutes.

**Comment by garronej** [comment]
It's implemented in the last Onyxia release:  

https://github.com/InseeFrLab/onyxia/blob/21ab8725591eed81d54de7e2c15c4c771572d3f7/web/src/core/ports/OnyxiaApi/XOnyxia.ts#L70-L71  

You have both the access token and refresh token.

**Comment by titigmr** [comment]
Nice! Thanks!
